export interface FormData {
    accountType: string,
    companyName: string,
    firstName?: string,
    fullName?:string,
    lastName?: string,
    email: string,
    phone: string,
    industry: string,
    size?: string,
    projectType?: string,
    description: string,
    budgetMin?: string,
    budgetMax?: string,
    timeline?: string,
    howHeard?: string,
    loaction?:string,
    hourlyRate?: number,
    job?:string,
    clientAdditionalInfo: string,
  }